# Generated by Django 3.2.6 on 2021-09-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1993-03-13'),
            preserve_default=False,
        ),
    ]
